### ISSUE TITLE
Installation?

### ISSUE THREAD

**Issue by contagon** [pacokwon/obsidian-lds-scriptures-plugin#1]
Hey, thanks for your work on this! Excited to give it a spin.

I was wondering if you have any recommendations for installation? The README seems to be missing installation instructions and I don't believe the plugin is in the obsidian community plugin window.

**Comment by pacokwon** [comment]
Hi, thank you for showing interest! TLDR; I'm trying to publish it to obsidian community plugin, and I'll try to make it happen soon.

Although the plugin is not "complete" in any way, I've implemented the essential features and submitted the plugin to publish it to the obsidian community plugins.

Unfortunately, [my first PR about a month ago](https://github.com/obsidianmd/obsidian-releases/pull/1978) was not getting any feedback after a single exchange. So after several weeks of waiting, I opened a [new one](https://github.com/obsidianmd/obsidian-releases/pull/2045) and I'm hoping it makes it.

Though it got me wondering, how did you find this plugin?

**Comment by McFarius** [comment]
Hi, I've also been interested in this project. Have not seen any traction with this project being approved as a community plugin, so I wanted to try a manual install to test it.

With no install directions yet, I attempted to install with the following steps:
I have downloaded all three files, added them to a folder, and added the folder to the plugins folder for the vault.
The plugin reflects in the community plugins tab. I enabled the plugin.

Issue:
The plugin does not create a settings tab in the community plugins section to edit any settings in the plugin (not sure if there are any to edit/if this is typical for this plugin or not. Some do not have settings to edit)
No option to install the translation files appears in any way when enabling or attempting to use the plugin
The syntax in the readme file has no effect when trying to create callouts.

Could you advise on any ways to troubleshoot any of these issues?

Love the concept and hope this gets approved soon as an official community plugin!

**Comment by pacokwon** [comment]
@McFarius Oh hi, yeah the experience has been so frustrating. It's been almost two months since I opened the older PR (which is closed now).

I'll get back to you on this later, I have a couple of church meetings today :)

One thing you *can* try while you're waiting is to build the artifacts yourself using `npm build`.

I'll come back and see if any issues are there with the release artifacts.

Thank you for showing your interest in this project!

**Comment by pacokwon** [comment]
@McFarius This plugin does have a settings tab, so it's probably a bug if it doesn't appear.

Can you try again with the new assets and also tell me your environment?

Currently it's only been tested on my machine only (Arch Linux x86), so it might happen to be a platform related bug

The translations are automatically installed as you select a translation to use, so there is no manual install/uninstall button as of now.

Let me know anything else that troubles you. Thanks!

**Comment by McFarius** [comment]
I tried again with the new assets and it now work! Only on the desktop version, though. 
Devices tested on are my Linux x86 desktop (Nobara), Windows x86, and two different android devices, all of them use syncthing to unify notes and plugins. 
The desktop clients work great, the mobile devices do not allow you to enable the plugin. Not the end of the world, since they still display the callouts properly, once I create them on the desktop version.
Thanks for the hard work! Hope it gets approved real soon!

**Comment by pacokwon** [comment]
Oh that is so good to hear!

The mobile versions wouldn't work right now because this plugin uses node's apis for some filesystem operations.

Hope you enjoy the plugin! Again, thanks for showing your interest.

**Comment by briandbezerra** [comment]
I have also been watching this development closely. I have been trying to find a way to study and Mark my scriptures in Obsidian but have the cross references still available. Is that possible with your plugin?

**Comment by pacokwon** [comment]
After about 1.5 months, the plugin is finally [merged](https://github.com/obsidianmd/obsidian-releases/pull/2045)!

Installation instructions have been added to the README, and the plugin can be installed from Obsidian's Community Plugins tab.

**Comment by briandbezerra** [comment]
Congratulations! Have a great mission!
